FROM apache/airflow:2.8.0-python3.11

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    wget \
    gnupg \
    curl \
    gosu \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libdbus-1-3 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libpango-1.0-0 \
    libcairo2 \
    poppler-utils \
    tesseract-ocr \
    tesseract-ocr-rus \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

USER root
RUN rm /tmp/requirements.txt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir -p /opt/airflow/logs/scheduler /opt/airflow/logs/dag_processor_manager \
    && chown -R 50000:0 /opt/airflow/logs \
    && chmod -R 775 /opt/airflow/logs

USER airflow
RUN playwright install chromium

ENTRYPOINT ["/entrypoint.sh"]

